server:
  servlet:
    context-path: /siteware

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Teste
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger